### ISSUE TITLE
make error in onvm directory

### ISSUE THREAD

**Issue by IndranilRoy80133** [sdnfv/openNetVM#68] opened 2019-02-25 03:07 UTC
I am following the installation instructions and when it was instructed to enter the onvm directory and use the make command, I am getting the following errors.

/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:108:18: error: ‘struct rte_eth_rxmode’ has no member named ‘header_split’
                 .header_split   = 0,                    /* header split disabled */
                  ^~~~~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:109:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_ip_checksum’
                 .hw_ip_checksum = 1,                    /* IP checksum offload enabled */
                  ^~~~~~~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:109:35: warning: excess elements in struct initializer
                 .hw_ip_checksum = 1,                    /* IP checksum offload enabled */
                                   ^
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:109:35: note: (near initialization for ‘port_conf.rxmode’)
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:110:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_vlan_filter’
                 .hw_vlan_filter = 0,                    /* VLAN filtering disabled */
                  ^~~~~~~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:110:35: warning: excess elements in struct initializer
                 .hw_vlan_filter = 0,                    /* VLAN filtering disabled */
                                   ^
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:110:35: note: (near initialization for ‘port_conf.rxmode’)
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:111:18: error: ‘struct rte_eth_rxmode’ has no member named ‘jumbo_frame’
                 .jumbo_frame    = 0,                    /* jumbo frame support disabled */
                  ^~~~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:111:35: warning: excess elements in struct initializer
                 .jumbo_frame    = 0,                    /* jumbo frame support disabled */
                                   ^
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:111:35: note: (near initialization for ‘port_conf.rxmode’)
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:112:18: error: ‘struct rte_eth_rxmode’ has no member named ‘hw_strip_crc’
                 .hw_strip_crc   = 1,                    /* CRC stripped by hardware */
                  ^~~~~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:112:35: warning: excess elements in struct initializer
                 .hw_strip_crc   = 1,                    /* CRC stripped by hardware */
                                   ^
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:112:35: note: (near initialization for ‘port_conf.rxmode’)
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:142:10: error: ‘const struct rte_eth_txconf’ has no member named ‘txq_flags’
         .txq_flags      = 0,
          ^~~~~~~~~
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:142:27: warning: initialized field overwritten [-Woverride-init]
         .txq_flags      = 0,
                           ^
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:142:27: note: (near initialization for ‘tx_conf.tx_free_thresh’)
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c: In function ‘init’:
/home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:171:9: warning: ‘rte_eth_dev_count’ is deprecated [-Wdeprecated-declarations]
         total_ports = rte_eth_dev_count();
         ^~~~~~~~~~~
In file included from /home/indranil/openNetVM/onvm/onvm_mgr/../onvm_nflib/onvm_includes.h:92:0,
                 from /home/indranil/openNetVM/onvm/onvm_mgr/../onvm_mgr/onvm_args.h:57,
                 from /home/indranil/openNetVM/onvm/onvm_mgr/../onvm_mgr/onvm_init.h:73,
                 from /home/indranil/openNetVM/onvm/onvm_mgr/onvm_init.c:52:
/home/indranil/openNetVM/dpdk/x86_64-native-linuxapp-gcc/include/rte_ethdev.h:1474:10: note: declared here
 uint16_t rte_eth_dev_count(void);
          ^~~~~~~~~~~~~~~~~
/home/indranil/openNetVM/dpdk/mk/internal/rte.compile-pre.mk:114: recipe for target 'onvm_init.o' failed
make[2]: *** [onvm_init.o] Error 1
/home/indranil/openNetVM/dpdk/mk/rte.extapp.mk:14: recipe for target 'all' failed
make[1]: *** [all] Error 2
/home/indranil/openNetVM/dpdk/mk/rte.extsubdir.mk:21: recipe for target 'onvm_mgr' failed
make: *** [onvm_mgr] Error 2

**Comment by koolzz** [comment] 2019-02-25 03:11
Hi @IndranilRoy80133, This looks like you have a new dpdk version and old onvm code.

Which version of openNetVM and dpdk are you using?

**Comment by IndranilRoy80133** [comment] 2019-02-25 03:16
How can I check the version?

**Comment by IndranilRoy80133** [comment] 2019-02-25 03:19
dpdk version is 18.11.1-rc1

**Comment by koolzz** [comment] 2019-02-25 03:23
Okay so you're using our latest dpdk version, you should checkout the dev branch and it should compile

**Comment by adityadhakal** [comment] 2019-02-25 03:38
Hi @koolzz do the `develop` branch have throughput issue which we reported on slack or this is a different version of OpenNetVM.

**Comment by koolzz** [comment] 2019-02-25 03:43
@adityadhakal We're not sure were the regression issue comes from yet. The issue reported above is simply due to using a new version of dpdk but using an old version of openNetVM with that. Updates for dpdk18.11 can be seen [here](https://github.com/sdnfv/openNetVM/commit/abe77ad9f75829a0d1cd18fe57ebbaae87a7c4ac)

**Comment by koolzz** [comment] 2019-02-26 18:05
Assuming that solved your issue, closing this.

**Closed by koolzz** 2019-02-26 18:05 UTC
