### ISSUE TITLE
Need Help to Recover from Errors Caused Example Programs 

### ISSUE THREAD

**Issue by haochenpan** [sdnfv/openNetVM#90] opened 2019-03-31 20:41 UTC
Hi all,

I believe I have set up openNetVM correctly. However, when I fire up `load_generator` along with `basic_monitor`, usually after around 1-30s, the manager threads dies (in another terminal) without giving any info. When I try to fire it up again, I always get:

> my_user_name@server-name-8:~$ ~/openNetVM/onvm/go.sh 0,1,2 1 0xF8 -s stdout
> EAL: Detected 8 lcore(s)
> EAL: Detected 1 NUMA nodes
> EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: Probing VFIO support...
> EAL: Cannot allocate memzone list
> EAL: FATAL: Cannot init memzone
> EAL: Cannot init memzone"

I am trying to figure out why and how to recover from this, I tried `sudo rm /mnt/huge/* -rf` and checked there are huge pages free (see below). Right now, I have no choice but open up one after another virtual machines.
> cat /proc/meminfo | grep Huge
> AnonHugePages:         0 kB
> HugePages_Total:    1024
> HugePages_Free:      965
> HugePages_Rsvd:        0
> HugePages_Surp:        0
> Hugepagesize:       2048 kB

**Steps to reproduce**
when I can normally fire up the manager, I run
`nohup ~/openNetVM/examples/start_nf.sh basic_monitor 7 -p 100000 &`
`nohup ~/openNetVM/examples/start_nf.sh load_generator 1 -d 7 &` then I get the error and can never recover, even I tried to restart the machine, bind `ONVM_NIC_PCI` and run `setup_environment.sh`again.

**Environment**

- OS:  Google Cloud Platform Ubuntu 14.04 LTS
- Spec: 16 vCPUs (it appears as 8 in openNetVM), 32 GB Mem
- onvm version:  from the current master branch
- dpdk version:  from the current master branch (v18.11)
- other info:  Here is the [setup script](https://pastebin.com/NbifZutY) for installing dependecies and openNetVM.

**In Addition...**
By the way, here are the outputs when I run `simple_forward` along with `speed_tester` examples, which I consider they are running fine (correct me if I am wrong).

>  my_user_name@server-name-8:~$ ~/openNetVM/onvm/go.sh 0,1,2 1 0xF8 -s stdout
> EAL: Detected 8 lcore(s)
> EAL: Detected 1 NUMA nodes
> EAL: Multi-process socket /var/run/dpdk/rte/mp_socket
> EAL: No free hugepages reported in hugepages-1048576kB
> EAL: Probing VFIO support...
> EAL: PCI device 0000:00:04.0 on NUMA socket -1
> EAL:   Invalid NUMA socket, default to 0
> EAL:   probe driver: 1af4:1000 net_virtio
> EAL: Error: Invalid memory
> WARNING: requested port 0 not present - ignoring
> Registered 5 cores for NFs: 3, 4, 5, 6, 7
> Creating mbuf pool 'MProc_pktmbuf_pool' [32767 mbufs] ...
> Creating mbuf pool 'NF_INFO_MEMPOOL' ...
> Creating mbuf pool 'NF_MSG_MEMPOOL' ...
> 
> Checking link statusdone
> Default service chain: send to sdn NF
> cur_index:1, action:2, destination:1
> 
> APP: Finished Process Init.
> APP: 3 cores available in total
> APP: 1 cores available for handling manager RX queues
> APP: 1 cores available for handling TX queues
> APP: 1 cores available for handling stats
> APP: Core 1: Running TX thread for NFs 1 to 127
> APP: Core 2: Running RX thread for RX queue 0
> APP: Core 0: Running master thread
> APP: Stats verbosity level = 1

Then I run, `nohup ~/openNetVM/examples/start_nf.sh simple_forward 2 -d 1 &`
`nohup ~/openNetVM/examples/start_nf.sh speed_tester 1 -d 2 -c 16000 &` so I get
![image](https://user-images.githubusercontent.com/32943456/55294466-57a14300-53d0-11e9-9c4d-2bec4ada65fa.png)

I can run `simple_forward` with `load_generator` just fine, but with some rx and tx dropped (I am also wondering why).

Best wishes,
Roger

**Comment by koolzz** [comment] 2019-03-31 20:45
Hi @haochenpan,

I didn't test this yet but here are some ideas:

The load_gen -> basic_monitor probably crashes the manager as it tries to send packets out of the NIC and the port probably isn't set up (we should fix this crash and make sure)

To recover from the `EAL: Cannot init memzone` you usually just have to ensure you've killed all your running NFs. In this case you would have to stop the basic_monitor and load_generator and then you'll be able to relaunch the onvm_mgr

**Comment by haochenpan** [comment] 2019-03-31 20:55
Hi @koolzz ,

For the `EAL` problem, you are right! I forgot to check `top` and kill threads.
For the `load_gen -> basic_monitor` problem, are you suggesting lines 172-173 of `monitor.c` are causing the problem? just curious, reply if you have time. 

Thank you for your timely reply!
Roger

**Comment by koolzz** [comment] 2019-03-31 21:06
You welcome, 

The problem is both there and in our [port tx processing function](https://github.com/sdnfv/openNetVM/blob/develop/onvm/onvm_nflib/onvm_pkt_common.c#L260) because we don't actually check if that port is allocated. I think port_buf just isn't a valid address which causes a segfault.

**Comment by koolzz** [comment] 2019-03-31 22:39
Are you experiencing constant drops or just the batch in the begging being dropped? If its constant you might need to adjust the packet rate, check README for more instructions.  

_As a note_, the load generator NF isn't as well tested as something like Pktgen so there might be some issues with it, we provide it more as a convenient example rather than a concrete performance benchmark.

**Comment by haochenpan** [comment] 2019-03-31 22:51
Not constant drops, around 500 packets / 30s,  I will check README though. 
Thanks, I will submit a PR if I have found something : )

**Comment by koolzz** [comment] 2019-03-31 22:55
In that case could just be that the processing isn't fast enough so you see occasional drops. Yeah. definitely, we're always happy to see new contributors.

Closing as the original question is resolved.

**Closed** 2019-03-31 22:55 UTC
Labels: bug :bug:
